In [ ]:
#import Pkg
#Pkg.add("DataFrames")
#Pkg.add(["CSV","Plots"])  # multiple at once
using Pkg
using DataFrames, CSV, Plots

ArgumentError: ArgumentError: Package pkg not found in current path.
- Run `import Pkg; Pkg.add("pkg")` to install the pkg package.

In [ ]:
	x = 1          # Int64
	y = 1.0        # Float64
	z = 2 + 3im    # Complex{Int64}



Base.Meta.ParseError: ParseError:
# Error @ d:\julia_work\Short Course\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_W1sZmlsZQ==.jl:5:2

	?print
#	╙ ── not a unary operator

In [ ]:
1 + 5
2 * 3
4 / 2
sqrt(9); exp(1); log(10)
round(1.2)

2.302585092994046

In [11]:
v = Float64[]          # empty
v1 = zeros(5)
v2 = ones(2)
append!(v1, v2)
v3 = collect(range(1, stop=2, length=5))


5-element Vector{Float64}:
 1.0
 1.25
 1.5
 1.75
 2.0

In [ ]:
A = [1 2 3; 4 5 6]
size(A), ndims(A), eltype(A)
R = reshape(range(0, 1, length=4), 2, 2)

2×2 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 2, 2) with eltype Float64:
 0.0       0.666667
 0.333333  1.0

In [ ]:
A = [1 2 3; 4 5 6]
A[1, :]   # first row
A[:, 2]   # second column
A[[1,2], [1,3]]

2-element Vector{Int64}:
 2
 5

In [20]:
function f(x, y, z)
    x + y + z
	end

f(1,2,3)


6

In [22]:
f2(x, y, z) = x + y + z

f(1,1,0)


2

In [23]:
weighted(x, y; a=1, b=2) = a*x + b*y
weighted(1,2)

5

In [24]:
map(x -> x + 1, [1,2,3])
map([1,2,3]) do x
	x + 1
	end

3-element Vector{Int64}:
 2
 3
 4

In [25]:
function stats(a, b, c)
		s = a + b + c
		p = a * b * c
		return s, p
end
s, p = stats(1,2,3)

(6, 6)

In [ ]:
function ineq(x, y)
	if x > y
	2
	elseif x < y
	1
	else
	0
	end
end

ineq(1,0)

0

In [28]:
j = 3
while j > 0
    println(j^2)
	j -= 1
end
			


9
4
1


In [29]:
for k in 1:3
	println(k^2)
end

1
4
9


In [31]:
f(y) = y > 0 ? y + 1 : throw(DomainError(y, "y must be > 0"))

result = try
    f(2)
catch e
    if e isa DomainError
        @warn "caught DomainError" exception=e
        NaN              # or `nothing` / `missing`
    else
        rethrow()
    end
end



3

In [ ]:
x=3
(x == 0) && error("x must be nonzero")
(x <= 5) || return 0


false

In [38]:
using Random
Random.seed!(1234)
rand()           # U(0,1)
rand(5)          # vector
randn(2,2)       # N(0,1) matrix



2×2 Matrix{Float64}:
 2.05476   -0.304901
 0.324893   0.461695

In [24]:
open("example.txt", "w") do io
    write(io, "hello world")
end
lines = readlines("example.txt")

1-element Vector{String}:
 "hello world"

In [ ]:
homedir()
pwd()
readdir()
pwd()
readdir()

11-element Vector{String}:
 "Blog"
 "Book"
 "Book_v1.5"
 "Computational"
 "Dynare Guide"
 "Matlab_to_Julia"
 "Short Course"
 "_gsdata_"
 "data.csv"
 "julia_depot"
 "testgsl.j"

In [42]:
using CSV, DataFrames
CSV.write("data.csv", DataFrame(x=1:3, y=rand(3)))
df = CSV.read("data.csv", DataFrame)

3×2 DataFrame
 Row │ x      y          
     │ Int64  Float64    
─────┼───────────────────
   1 │     1  0.578232
   2 │     2  0.727935
   3 │     3  0.00744801

In [44]:
using Dates
Date(2015,5,1)
DateTime(2016,3,10,11)
d = Date("2016-05-05", DateFormat("y-m-d"))
year(d), month(d)

(2016, 5)

In [47]:
using DataFrames
DF = DataFrame(x=range(0, 1, length=10), y=randn(10))
first(DF, 5)
describe(DF)

2×7 DataFrame
 Row │ variable  mean       min       median     max      nmissing  eltype   
     │ Symbol    Float64    Float64   Float64    Float64  Int64     DataType 
─────┼───────────────────────────────────────────────────────────────────────
   1 │ x          0.5        0.0       0.5       1.0             0  Float64
   2 │ y         -0.270897  -1.54985  -0.651723  2.23396         0  Float64

In [59]:
using Plots
x = range(0, stop=1, length=100); y = randn(100)
p=plot(x, y, title="Basic Plot")

savefig(p, "simple_plot.png")

"d:\\julia_work\\simple_plot.png"

In [49]:
struct Point{T}
x::T; y::T
end
norm(p::Point{T}) where {T<:Real} = sqrt(p.x^2 + p.y^2)

norm (generic function with 1 method)

In [52]:
area(r::Real) = pi*r^2
area(w::Real, h::Real) = w*h

area(2)
area(2,3)

6

In [53]:
x = 1:5; y = 2:6
x .+ y


3:2:11

In [54]:
f(t) = t^2
f.(x)

5-element Vector{Int64}:
  1
  4
  9
 16
 25

In [55]:
x = 2
val = x > 0 ? "positive" : "nonpositive"

ans = if x < -1
    :low
elseif x <= 1
    :mid
else
    :high
end


:high

In [56]:
# vector and matrix comprehensions: vector and matrix allocation
	v = [i^2 for i in 1:5]
	M = [i*j for i in 1:3, j in 1:3]


3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [57]:
# generators (lazy)
sum(i^2 for i in 1:1000)	

333833500

In [60]:
#PRACTICE:
#T1.1 Task
x = 1:10
y = 2 .* x .+ 1
sum(y)
using Statistics
mean(y) 

12.0

In [61]:
#T1.2. Task

f(x) = x^2 + 3x + 1
f.(0:5)
map(x -> x % 2 == 0 ? x÷2 : 3x+1, 1:10)

10-element Vector{Int64}:
  4
  1
 10
  2
 16
  3
 22
  4
 28
  5

In [36]:
#T.1.3
using DataFrames, Random, Statistics
Random.seed!(123)
df = DataFrame(id = 1:8, x = randn(8))
df.meanx = fill(mean(df.x), nrow(df))     # make a constant column
first(df, 5)

5×3 DataFrame
 Row │ id     x          meanx     
     │ Int64  Float64    Float64   
─────┼─────────────────────────────
   1 │     1   0.808288  -0.386921
   2 │     2  -1.12207   -0.386921
   3 │     3  -1.10464   -0.386921
   4 │     4  -0.416993  -0.386921
   5 │     5   0.287588  -0.386921

In [37]:
#T1.s1
weighted(x, y; a=1, b=2) = a*x + b*y
weighted.(1:5, 2:6; a=2, b=3)

5-element Vector{Int64}:
  8
 13
 18
 23
 28

In [38]:
#T1s.2
using BenchmarkTools
g(v) = sum(@. 2v + 1)
x = rand(10_000)
@btime g($x)

  2.556 μs (3 allocations: 78.21 KiB)


20075.185126309843

In [39]:
	using BenchmarkTools, Random
		Random.seed!(0)
		x = rand(1_000_000); y = rand(1_000_000)
		
		axpy_naive(a, x, y) = a .* x .+ y
		
		function axpy!(y, a, x)
		@inbounds @simd for i in eachindex(x, y)
		y[i] = a*x[i] + y[i]
		end
		return y
		end
		
		@btime axpy_naive(2.0, $x, $y);
		@btime ($y .= 2.0 .* $x .+ $y);
		@btime axpy!($y, 2.0, $x);

  1.218 ms (3 allocations: 7.63 MiB)
  228.200 μs (0 allocations: 0 bytes)
  229.700 μs (0 allocations: 0 bytes)


In [41]:
	using BenchmarkTools
		x = rand(1_000_000); y = rand(1_000_000); z = similar(x)
		
		f_bad(x, y) = sin.(x) + x.^2 + 3 .* y .+ 1
		f_dot!(z, x, y) = (z .= @. sin(x) + x^2 + 3y + 1)
		
		@btime f_bad($x,$y);
		@btime f_dot!($z,$x,$y);
		
		@btime f_bad(@view($x[2:end-1]), @view($y[2:end-1]));
		@btime f_dot!(@view($z[2:end-1]), @view($x[2:end-1]), @view($y[2:end-1]));

  9.836 ms (15 allocations: 38.15 MiB)
  3.607 ms (0 allocations: 0 bytes)
  10.037 ms (15 allocations: 38.15 MiB)
  3.875 ms (0 allocations: 0 bytes)


In [43]:
	x = rand(2_000_000); k = 50
		
		ma_naive(x,k) = [ mean(@view x[i-k+1:i]) for i in k:length(x) ]
		
		function ma_cumsum(x, k)
		s = cumsum(x)
		y = s[k:end] .- vcat(0.0, s[1:end-k])
		y ./= k
		return y
		end
		
		function ma_loop!(y, x, k)
		s = sum(@view x[1:k])
		y[1] = s / k
		for i in (k+1):length(x)
		s += x[i] - x[i-k]
		y[i-k+1] = s / k
		end
		return y
		end
		
		y = similar(x, length(x)-k+1)

1999951-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0